# ###############################################
set (CPF_TARGET_OS "Linux")
set (CPF_TARGET_OS_LINUX 1)

set (CPF_TARGET_CPU "Intel")
set (CPF_TARGET_CPU_SIZE "${CPF_ARCHITECTURE_SIZE}")
set (CPF_TARGET_CPU_DIR "x${CPF_ARCHITECTURE_SIZE}")


# TODO: Flesh this out.
set (CPF_TARGET_PLATFORM "Linux")
set (CPF_TARGET_LINUX 1)

if (CMAKE_SYSTEM_PROCESSOR STREQUAL "x86_64" OR CMAKE_SYSTEM_PROCESSOR STREQUAL "AMD64")
	set (CPF_TARGET_ARCHITECTURE "x86_64")
endif ()
