import iUnknown from GOM;
module CPF;

interface iClipboard : GOM::iUnknown
{
	const class_id kDefault("CPF::iClipboard::Default");

	result GetClipboardText(s32* count, char* text);
	result SetClipboardText(const char* text);
};
