import iInputDevice from CPF::Application;
import KeyModifiers from CPF::Application;
module CPF;

interface iKeyboardDevice : iInputDevice
{
	const class_id kDefault("Cpf::iKeyboardDevice::Default");

	/**
	* @brief Gets the modifier keys currently set.
	* @param [in,out] modifiers The output to the modifier value.
	* @return The result code.
	*/
	result GetModifiers(KeyModifier* modifiers);
};
