import iApplication from Application;
module CPF;

struct WindowDesc;
interface iWindow;

interface iWindowedApplication : iApplication
{
	/**
	* @brief Determine if the application is supposed to still be running.
	* @return True if the application is still running, false if a quit request has been made.
	*/
	bool IsRunning();

	/**
	* @brief Issues a quit request.
	*/
	void Quit();

	/**
	* @brief Polls the application for events.
	* @return A result code.
	*/
	result Poll();

	/**
	* @brief Waits for an application event.
	* @return A result code.
	*/
	result Wait();

	/**
	* @brief Creates a new CPF_STDCALL.
	* @param desc The window descriptor.
	* @param [in,out] outWindow The window output variable.
	* @return A result code.
	*/
	result Create(const WindowDesc* desc, iWindow** outWindow);

	/**
	* @brief Gets input manager.
	* @return The input manager.
	*/
	iInputManager* GetInputManager();
};
