import iUnknown from GOM;
import Access from CPF::IO;
module CPF::IO;

interface iStream;

interface iFile : GOM::iUnknown
{
	callback OnComplete = void(result value, void* context);
	void Exists(const char* name, void* context, OnComplete cb);
	void Delete(const char* name, void* context, OnComplete cb);
	callback OnCreate = void(result value, iStream* stream, void* context);
	void Create(const char* name, Access access, void* context, OnCreate cb);
}
