import iUnknown from GOM;
import Access from CPF::IO;
import Origin from CPF::IO;
module CPF::IO;

interface iStream : GOM::iUnknown
{
	Access GetAccess();
	bool CanSeek();
	bool CanRead();
	bool CanWrite();

	callback OnComplete = void (result value);

	void Close(OnComplete cb);
	void Flush(OnComplete cb);

	callback OnPosition = void(result value, s64 position);
	void GetPosition(OnPosition cb);

	callback OnLength = void(result value, s64 length);
	void GetLength(OnLength cb);

	callback OnSeek = void(result value);
	void Seek(s32 offset, Origin origin, OnSeek cb);

	//
	callback OnRead = void(result value, s64 count);
	void Read(void* outBuffer, s64 length, OnRead cb);

	callback OnWrite = void(result value, s64 count);
	void Write(const void* inBuffer, s64 length, OnWrite cb);
}
