module CPF::Graphics;

enum Format : s32;

struct DepthStencilValue
{
	f32 mDepth;
	u8 mStencil;
};

union ClearValueData
{
	f32 mColor[4];
	DepthStencilValue mDepthStencil;
}

struct ClearValue
{
	Format mFormat;
	ClearValueData mValue;
};
