//////////////////////////////////////////////////////////////////////////
#pragma once
#include "Configuration.hpp"

namespace Cpf
{
	/** @brief Keyboard scan codes. */
	enum class ScanCode : int32_t
	{
		e0 = '0',
		e1 = '1',
		e2 = '2',
		e3 = '3',
		e4 = '4',
		e5 = '5',
		e6 = '6',
		e7 = '7',
		e8 = '8',
		e9 = '9',
		eA = 'a',
		eB = 'b',
		eC = 'c',
		eD = 'd',
		eE = 'e',
		eF = 'f',
		eG = 'g',
		eH = 'h',
		eI = 'i',
		eJ = 'j',
		eK = 'k',
		eL = 'l',
		eM = 'm',
		eN = 'n',
		eO = 'o',
		eP = 'p',
		eQ = 'q',
		eR = 'r',
		eS = 's',
		eT = 't',
		eU = 'u',
		eV = 'v',
		eW = 'w',
		eX = 'x',
		eY = 'y',
		eZ = 'z',
		eReturn = 40,
		eEscape = 41,
		eBackspace = 42,
		eTab = 43,
		eSpace = 44,
		ePrintScreen = 70,
		eScrollLock = 71,
		ePause = 72,
		eInsert = 73,
		eHome = 74,
		ePageUp = 75,
		eDelete = 76,
		eEnd = 77,
		ePageDown = 78,
		eRight = 79,
		eLeft = 80,
		eDown = 81,
		eUp = 82,
		eKPBackspace = 187,
	};
}
