import Format from Graphics;
import LoadOp from Graphics;
import StoreOp from Graphics;
import SampleDesc from Graphics;
import ResourceState from Graphics;
import AttachmentRef from Graphics;

module CPF::Graphics;

struct AttachmentDesc
{
	s32 mFlags; // TODO:
	Format mFormat;
	SampleDesc mSamples;
	LoadOp mLoadOp;
	StoreOp mStoreOp;
	LoadOp mStencilLoadOp;
	StoreOp mStencilStoreOp;
	ResourceState mStartState;
	ResourceState mFinalState;
}
