import Graphics;
import RenderTargetBlendStateDesc from Graphics;

module CPF::Graphics;

struct BlendStateDesc
{
	bool mAlphaToCoverage = false;
	bool mIndependentBlend = false;
	RenderTargetBlendStateDesc mRenderTarget[8] = {
		default RenderTargetBlendStateDesc,
		default RenderTargetBlendStateDesc,
		default RenderTargetBlendStateDesc,
		default RenderTargetBlendStateDesc,
		default RenderTargetBlendStateDesc,
		default RenderTargetBlendStateDesc,
		default RenderTargetBlendStateDesc,
		default RenderTargetBlendStateDesc
	};
}
