module CPF::Graphics;

enum Format : s32;
enum InputClassification : s32;

struct ElementDesc
{
	const char* mpSemantic;
	s32 mIndex;
	Format mFormat;
	s32 mSlot;
	s32 mOffset;
	InputClassification mClass;
	s32 mInstanceStepping;
}
