import Format from CPF::Graphics;
import ImageFlags from CPF::Graphics;
import SampleDesc from CPF::Graphics;
import ResourceState from CPF::Graphics;

module CPF::Graphics;

struct ImageDesc
{
	s32 mWidth;
	s32 mHeight;
	s32 mDepth;
	s32 mMipLevels;
	Format mFormat;
	SampleDesc mSamples;
	ResourceState mState;
	ImageFlags mFlags;
};
