import BindingType from CPF::Graphics;
import ParamFlags from CPF::Graphics;
import ParamVisibility from CPF::Graphics;

module CPF::Graphics;

struct ParamBindingDesc
{
	BindingType mType;
	s32 mIndex;
	s32 mCount;
	ParamFlags mFlags;
	ParamVisibility mVisibility;
};
