import BlendFunc from Graphics;
import BlendOp from Graphics;
import LogicOp from Graphics;
import WriteMask from Graphics;

module CPF::Graphics;

struct RenderTargetBlendStateDesc
{
	bool mBlending;
	bool mLogicOps;
	BlendFunc mSrcBlend;
	BlendFunc mDstBlend;
	BlendOp mBlendOp;
	BlendFunc mSrcBlendAlpha;
	BlendFunc mDstBlendAlpha;
	BlendOp mBlendOpAlpha;
	LogicOp mLogicOp;
	WriteMask mWriteMask;
}

defaults RenderTargetBlendStateDesc
{
	mBlending: false;
	mLogicOps: false;
	mSrcBlend: BlendFunc::eSrcColor;
	mDstBlend: BlendFunc::eDstColor;
	mBlendOp: BlendOp::eAdd;
	mSrcBlendAlpha: BlendFunc::eSrcAlpha;
	mDstBlendAlpha: BlendFunc::eDstAlpha;
	mBlendOpAlpha: BlendOp::eAdd;
	mLogicOp: LogicOp::eCopy;
	mWriteMask: WriteMask::eAll;
}
