import BlendFunc from CPF::Graphics;
import BlendOp from CPF::Graphics;
import LogicOp from CPF::Graphics;
import WriteMask from CPF::Graphics;

module CPF::Graphics;

struct RenderTargetBlendStateDesc
{
	bool mBlending = false;
	bool mLogicOps = false;
	BlendFunc mSrcBlend = BlendFunc::eSrcColor;
	BlendFunc mDstBlend = BlendFunc::eDstColor;
	BlendOp mBlendOp = BlendOp::eAdd;
	BlendFunc mSrcBlendAlpha = BlendFunc::eSrcAlpha;
	BlendFunc mDstBlendAlpha = BlendFunc::eDstAlpha;
	BlendOp mBlendOpAlpha = BlendOp::eAdd;
	LogicOp mLogicOp = LogicOp::eCopy;
	WriteMask mWriteMask = WriteMask::eAll;
}
