module CPF::Graphics;

enum ResourceType : s32;
enum HeapType : s32;
enum ResourceState : s32;

struct ResourceDesc
{
	ResourceType mType;
	HeapType mHeapType;
	ResourceState mState;
	s32 mWidth;
	s32 mHeight;
};
