import FilterMode from Graphics;
import WrapMode from Graphics;

module CPF::Graphics;

struct SamplerDesc
{
	FilterMode mMinFilter;
	FilterMode mMagFilter;
	FilterMode mMipFilter;
	WrapMode mUWrap;
	WrapMode mVWrap;
	WrapMode mWWrap;
	f32 mLodMin;
	f32 mLodMax;
	f32 mLodBias;
};
