import Format from Graphics;
import SwapEffect from Graphics;
import SampleDesc from Graphics;

module CPF::Graphics;

struct SwapChainDesc
{
	Format mFormat;
	SwapEffect mSwapEffect;
	SampleDesc mMultiSample;
	s32 mBackBufferCount;
	bool mAllowFullscreen;
	bool mVSync;
};
