//////////////////////////////////////////////////////////////////////////
#pragma once
#include "Graphics/Utilities.hpp"

//////////////////////////////////////////////////////////////////////////
#include "CPF/Graphics/Format.hpp"

#include "CPF/Graphics/Range.hpp"

#include "CPF/Graphics/HeapType.hpp"
#include "CPF/Graphics/ImageDesc.hpp"
#include "CPF/Graphics/SwapEffect.hpp"
#include "CPF/Graphics/ImageFlags.hpp"
#include "CPF/Graphics/WindowData.hpp"
#include "CPF/Graphics/SubPassDesc.hpp"
#include "CPF/Graphics/SubResource.hpp"
#include "CPF/Graphics/ResourceDesc.hpp"
#include "CPF/Graphics/SwapChainDesc.hpp"
#include "CPF/Graphics/ResourceState.hpp"
#include "CPF/Graphics/AttachmentDesc.hpp"
#include "CPF/Graphics/RenderPassDesc.hpp"
#include "CPF/Graphics/FrameBufferDesc.hpp"
#include "CPF/Graphics/PipelineBindPoint.hpp"
#include "CPF/Graphics/RenderPassBeginDesc.hpp"
#include "CPF/Graphics/ResourceBindingDesc.hpp"

#include "CPF/Graphics/iBlob.hpp"
#include "CPF/Graphics/iFence.hpp"
#include "CPF/Graphics/iImage.hpp"
#include "CPF/Graphics/iShader.hpp"
#include "CPF/Graphics/iDevice.hpp"
#include "CPF/Graphics/iAdapter.hpp"
#include "CPF/Graphics/iResource.hpp"
#include "CPF/Graphics/iPipeline.hpp"
#include "CPF/Graphics/iInstance.hpp"
#include "CPF/Graphics/iImageView.hpp"
#include "CPF/Graphics/iSwapChain.hpp"
#include "CPF/Graphics/iIndexBuffer.hpp"
#include "CPF/Graphics/iCommandPool.hpp"
#include "CPF/Graphics/iVertexBuffer.hpp"
#include "CPF/Graphics/iCommandBuffer.hpp"
#include "CPF/Graphics/iConstantBuffer.hpp"
#include "CPF/Graphics/iResourceBinding.hpp"
