import iUnknown from CPF::GOM;
import Rectangle from CPF::Math;
module CPF::Graphics;

struct iDevice;
struct iConstantBuffer;
struct iResource;
struct iIndexBuffer;
struct iVertexBuffer;
struct iImage;
struct iImageView;
struct iSwapChain;
struct iCommandPool;
struct iSampler;
struct iResourceBinding;
struct iPipeline;

struct ResourceData;
struct Viewport;
struct RenderPassBeginDesc;

enum PrimitiveTopology : s32;
enum SubResource : s32;
enum ResourceState : s32;
enum DepthStencilClearFlag : s32;

enum CommandBufferType : s32
{
	ePrimary = 0,
	eSecondary = 1,
	eCompute = 2,
	eCopy = 3
}

failure AlreadyInRenderPass ("Graphics", "Already in render pass");
failure NotInRenderPass ("Graphics", "Not in a render pass");

interface iCommandBuffer : GOM::iUnknown
{
	void Begin(iCommandBuffer* primary);
	void End();

	void Reset(iCommandPool* pool);

	void UpdateSubResource(iResource* src, iResource* dst, const ResourceData* data);

	void CopyResource(iResource* src, iResource* dst);

	void ResourceBarrier(iResource* resource, ResourceState startStart, ResourceState endState);
	void ImageTransition(iImage* image, ResourceState startState, ResourceState endState, SubResource subResources);

	void SetResourceBinding(iResourceBinding* binding);
	void SetPipeline(iPipeline* pipeline);
	void SetViewports(s32 count, const Viewport* rects);
	void SetScissorRects(s32 count, const Math::Rectanglei* rects);
	void SetTopology(PrimitiveTopology topology);
	void SetVertexBuffers(s32 startSlot, s32 viewCount, iVertexBuffer** outVB);
	void SetIndexBuffer(iIndexBuffer* ib);
	void SetConstantBuffer(s32 index, iConstantBuffer* cb);
	void SetConstants(s32 index, s32 count, const void* data, s32 offset);
	void SetSampler(s32 index, iSampler* sampler);
	void SetImage(s32 index, iImage* image);

	void DrawInstanced(s32 vertsPerInstance, s32 instances, s32 startVert, s32 startInstance);
	void DrawIndexedInstanced(s32 vertsPerInstance, s32 instances, s32 startVert, s32 offset, s32 startInstance);

	// Render passes.
	result BeginRenderPass(RenderPassBeginDesc* rpbd);
	result NextSubPass();
	result EndRenderPass();

	// Secondary command buffer insertion.
	result Insert(s32 count, iCommandBuffer* const* icb);
}
