import iScheduler from CPF::Platform::Concurrency;

module CPF::Platform;

interface iThreadPool : iThreadController
{
	const class_id kCID("CPF::Platform::iThreadPool");

	result Initialize(s32 threadCount);
	void Shutdown();

	void Enqueue(WorkFunction func, void* context);

	iScheduler* GetScheduler();
}
