import Time from CPF;

module CPF::Platform;

const s32 MaxThreads = 128;

struct ThreadTimeInfo
{
	s32 mThreadCount;
	Time::Value mDuration;
	Time::Value mUserTime[MaxThreads];
	Time::Value mKernelTime[MaxThreads];
}
