# ###############################################
set (CPF_TARGET_OS "Darwin")
set (CPF_TARGET_OS_OSX 1)

set (CPF_TARGET_CPU "Intel")
set (CPF_TARGET_CPU_SIZE "${CPF_ARCHITECTURE_SIZE}")
set (CPF_TARGET_CPU_DIR "x${CPF_ARCHITECTURE_SIZE}")
set (CPF_TARGET_CPU_DIR "x64")


set (CPF_TARGET_PLATFORM "Darwin")
set (CPF_TARGET_DARWIN 1)

if (CMAKE_SYSTEM_PROCESSOR STREQUAL "x86_64" OR CMAKE_SYSTEM_PROCESSOR STREQUAL "AMD64")
	set (CPF_TARGET_ARCHITECTURE "x86_64")
endif ()
