import iRegistry from CPF::Plugin;
import iThreadController from CPF::Platform::Concurrency;

module CPF::Platform;

interface iLoadBalancer : iThreadController
{
    const class_id kCIDLoadBalance("CPF::Platform::LoadBalance");
    const class_id kCIDLoadBalanceMinimize("CPF::Platform::LoadBalanceMinimize");

    result SetControllers(s32 count, iThreadController** controllers);
    result GetControllers(s32* count, iThreadController** controllers);
    result RebalanceThreads();
}
