import iThreadController from CPF::Platform::Concurrency;

module CPF::Platform;

struct WorkContext;

interface iFence;
interface iWorkBuffer;

WorkFunction = void(const WorkContext* context, void* data);

interface iScheduler : iThreadController
{
	const class_id kCID ("CPF::Platform::iScheduler");

	result Initialize(s32 threadCount, WorkFunction init, WorkFunction shutdown, void* context);
	void Shutdown();

	void Execute(iWorkBuffer* buffer);
	void Submit(iFence* fence);
}
