import EnumFlagType from CPF;
module CPF::Platform::Desktop;

flags KeyModifier : s32
{
	eNone = 0,
	eLeftShift = 1<<0,
	eRightShift = 1<<1,
	eLeftControl = 1<<2,
	eRightControl = 1<<3,
	eLeftAlt = 1<<4,
	eRightAlt = 1<<5,
	eLeftOS = 1<<6,
	eRightOS = 1<<7,
	eNumLock = 1<<8,
	eCaps = 1<<9,
	eMode = 1<<10,
	eControl = 1<<2 | 1<<3,
	eShift = 1<<0 | 1<<1,
	eAlt = 1<<4 | 1<<5,
	eOS = 1<<6 | 1<<7
};
