# Setup the language dialect in use.
IF( CMAKE_GENERATOR STREQUAL Xcode )
	SET( CMAKE_XCODE_ATTRIBUTE_CLANG_CXX_LANGUAGE_STANDARD ${CPF_CPP_DIALECT} )
	SET( CMAKE_XCODE_ATTRIBUTE_CLANG_CXX_LIBRARY "libc++" )
ENDIF()
