#
if (CPF_SIMD_INSTRUCTION_SET STREQUAL "SSE")
	if (CPF_SIMD_INSTRUCTION_LEVEL STREQUAL "Reference")
		set (INSTRUCTION_SET_FLAG "-mno-sse")
	elseif (CPF_SIMD_INSTRUCTION_LEVEL STREQUAL "Sse1")
		set (INSTRUCTION_SET_FLAG "-msse")
	elseif (CPF_SIMD_INSTRUCTION_LEVEL STREQUAL "Sse2" OR
			CPF_SIMD_INSTRUCTION_LEVEL STREQUAL "Sse3" OR
			CPF_SIMD_INSTRUCTION_LEVEL STREQUAL "Sse4" OR
			CPF_SIMD_INSTRUCTION_LEVEL STREQUAL "Sse4.1" OR
			CPF_SIMD_INSTRUCTION_LEVEL STREQUAL "Sse4.2" OR
			CPF_SIMD_INSTRUCTION_LEVEL STREQUAL "Sse4a")
		set (INSTRUCTION_SET_FLAG "-msse2")
	elseif (CPF_SIMD_INSTRUCTION_LEVEL STREQUAL "Avx")
		set (INSTRUCTION_SET_FLAG "-mavx")
	elseif (CPF_SIMD_INSTRUCTION_LEVEL STREQUAL "Avx2")
		set (INSTRUCTION_SET_FLAG "-mavx2")
	else ()
		set (INSTRUCTION_SET_FLAG "-mno-sse")
	endif ()
else ()
	# TODO: Arm and others...
endif ()


#
set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${INSTRUCTION_SET_FLAG}")
