import Result from CPF::GOM;
module CPF::GOM;

success OK ("Core", "OK");
success None ("Core", "None");
failure Error ("Core", "Error");
failure UnknownInterface ("Core", "Unknown interface");
failure InvalidParameter ("Core", "Invalid parameter");
failure OutOfMemory ("Core", "Out of memory");
failure UnknownClass ("Core", "Unknown class");
failure NotImplemented ("Core", "Not implemented");
failure Invalid ("Core", "Invalid");
failure NotEnoughSpace ("Core", "Not enough space");
failure InUse ("Core", "In use");
failure NotInitialized ("Core", "Not initialized");
failure InitializationFailure ("Core", "Initialization failure");
failure OutOfRange ("Core", "Out of range");
failure DuplicateCID ("Core", "Duplicate CID");
failure RegistryError ("Core", "Registry error");
failure NotRunning ("Core", "Not running");
failure NotFound ("Core", "Not found");
failure AlreadyLoaded ("Core", "Already loaded");
failure NotRegistered ("Core", "CID not registered");

