module CPF::Graphics;

enum BlendFunc : s32
{
	eZero = 1,
	eOne,
	eSrcColor,
	eInvSrcColor,
	eSrcAlpha,
	eInvSrcAlpha,
	eDstAlpha,
	eInvDstAlpha,
	eDstColor,
	eInvDstColor,
	eSrcAlphaSat,
	eBlendFactor = 14,
	eInvBlendFactor,
	eSrc1Color,
	eInvSrc1Color,
	eSrc1Alpha,
	eInvSrc1Alpha
}
