import FillMode from CPF::Platform::Graphics;
import CullMode from CPF::Platform::Graphics;
import WindingOrder from CPF::Platform::Graphics;
import ConservativeRasterization from CPF::Platform::Graphics;

module CPF::Graphics;

struct RasterizerStateDesc
{
	FillMode mFillMode = FillMode::eSolid;
	CullMode mCullMode = CullMode::eBack;
	WindingOrder mWindingOrder = WindingOrder::eClockwise;
	s32 mDepthBias = 0;
	f32 mDepthBiasClamp = 0.0f;
	f32 mSlopeScaledDepthBias = 0.0f;
	bool mDepthClipping = true;
	bool mMultisampling = false;
	bool mAALines = false;
	s32 mForcedSampleCount = 0;
	ConservativeRasterization mConservativeRasterization = ConservativeRasterization::eOff;
};
