import Rectangle from CPF::Math;
import ClearValue from CPF::Platform::Graphics;

module CPF::Graphics;

struct iRenderPass;
struct iFrameBuffer;

struct RenderPassBeginDesc
{
	iRenderPass* mpRenderPass;
	iFrameBuffer* mpFrameBuffer;
	Math::Rectanglei mClipRect;
	int32_t mClearValueCount;
	const ClearValue* mpClearValues;
};
