import iUnknown from GOM;
module CPF::Plugin;

struct IID_CID
{
	u64 mIID;
	u64 mCID;
}

interface iRegistry;

interface iClassInstance : GOM::iUnknown
{
	result CreateInstance (iRegistry* registry, GOM::iUnknown* outer, [out] GOM::iUnknown** outInstance);
}
