//////////////////////////////////////////////////////////////////////////
#pragma once
#include "Graphics/Utilities.hpp"

//////////////////////////////////////////////////////////////////////////
#include "CPF/Platform/Graphics/Format.hpp"

#include "CPF/Platform/Graphics/Range.hpp"
#include "CPF/Platform/Graphics/HeapType.hpp"
#include "CPF/Platform/Graphics/Viewport.hpp"
#include "CPF/Platform/Graphics/ImageDesc.hpp"
#include "CPF/Platform/Graphics/ShaderType.hpp"
#include "CPF/Platform/Graphics/SwapEffect.hpp"
#include "CPF/Platform/Graphics/ImageFlags.hpp"
#include "CPF/Platform/Graphics/WindowData.hpp"
#include "CPF/Platform/Graphics/SamplerDesc.hpp"
#include "CPF/Platform/Graphics/iRenderPass.hpp"
#include "CPF/Platform/Graphics/SubPassDesc.hpp"
#include "CPF/Platform/Graphics/SubResource.hpp"
#include "CPF/Platform/Graphics/ResourceData.hpp"
#include "CPF/Platform/Graphics/iFrameBuffer.hpp"
#include "CPF/Platform/Graphics/ResourceDesc.hpp"
#include "CPF/Platform/Graphics/ResourceType.hpp"
#include "CPF/Platform/Graphics/SwapChainDesc.hpp"
#include "CPF/Platform/Graphics/ResourceState.hpp"
#include "CPF/Platform/Graphics/AttachmentDesc.hpp"
#include "CPF/Platform/Graphics/RenderPassDesc.hpp"
#include "CPF/Platform/Graphics/InputLayoutDesc.hpp"
#include "CPF/Platform/Graphics/FrameBufferDesc.hpp"
#include "CPF/Platform/Graphics/PrimitiveTopology.hpp"
#include "CPF/Platform/Graphics/PipelineBindPoint.hpp"
#include "CPF/Platform/Graphics/PipelineStateDesc.hpp"
#include "CPF/Platform/Graphics/RenderPassBeginDesc.hpp"
#include "CPF/Platform/Graphics/ResourceBindingDesc.hpp"
#include "CPF/Platform/Graphics/RenderTargetBlendStateDesc.hpp"

#include "CPF/Platform/Graphics/iBlob.hpp"
#include "CPF/Platform/Graphics/iFence.hpp"
#include "CPF/Platform/Graphics/iImage.hpp"
#include "CPF/Platform/Graphics/iShader.hpp"
#include "CPF/Platform/Graphics/iDevice.hpp"
#include "CPF/Platform/Graphics/iSampler.hpp"
#include "CPF/Platform/Graphics/iAdapter.hpp"
#include "CPF/Platform/Graphics/iResource.hpp"
#include "CPF/Platform/Graphics/iPipeline.hpp"
#include "CPF/Platform/Graphics/iInstance.hpp"
#include "CPF/Platform/Graphics/iImageView.hpp"
#include "CPF/Platform/Graphics/iSwapChain.hpp"
#include "CPF/Platform/Graphics/iIndexBuffer.hpp"
#include "CPF/Platform/Graphics/iCommandPool.hpp"
#include "CPF/Platform/Graphics/iVertexBuffer.hpp"
#include "CPF/Platform/Graphics/iCommandBuffer.hpp"
#include "CPF/Platform/Graphics/iConstantBuffer.hpp"
#include "CPF/Platform/Graphics/iResourceBinding.hpp"

#include "CPF/Platform/Graphics/BlendStateBuilder.hpp"
#include "CPF/Platform/Graphics/InputLayoutBuilder.hpp"
#include "CPF/Platform/Graphics/DepthStencilBuilder.hpp"
#include "CPF/Platform/Graphics/PipelineStateBuilder.hpp"
#include "CPF/Platform/Graphics/RasterizerStateBuilder.hpp"
